src/objects/c_Automation__mdt/c_Automation__mdt.object-meta.xml
<CustomObject>
    <description>A common object used to control automation of validation rules, process builder and triggers. Provide the RecordAPIName for a row, and define the settings you require to control the automation execution. Standard values are: Triggers, ValidationRules, ProcessBuilder
Access custom metadata in formula as $CustomMetadata.CustomMetadataTypeAPIName.RecordAPIName.FieldAPIName</description>
    <label>Automation Control</label>
    <pluralLabel>Automation Controls</pluralLabel>
</CustomObject>

src/objects/c_Automation__mdt/fields/Disable__c.field-meta.xml
<CustomField>
    <fullName>Disable__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Disable an automation facility</description>
    <inlineHelpText>Disable an automation facility</inlineHelpText>
    <label>Disable</label>
    <type>Checkbox</type>
</CustomField>

src/classes/c_AutomationControl_Test.cls
/**
 @Name: c_AutomationControl_Test.cls
 @Tests: c_AutomationControl
 @Description:
    Checks fundamental settings have not been removed an that code methods are working
@History
  VERSION     AUTHOR           DATE            DETAIL
  1.0         Matt Evans       7/12/2018       Initial commit
*/

@IsTest
private with sharing class c_AutomationControl_Test {
    @IsTest
    static void checkFundamentalCustomMetaDataTypes() {
        c_Automation__mdt[] d = [Select MasterLabel, DeveloperName,
                                    Disable__c
                                    FROM c_Automation__mdt
                                    WHERE DeveloperName = 'Triggers'];
        System.Assert(!d.IsEmpty(), 'Setting name "Triggers" is missing from Custom Meta Data "Automation Control". This is a mandatory setting. Add back!');
    }

    @IsTest
    static void codeCoverageAsWeCannotTestMetadataAPI() {
        c_AutomationControl.doNotFireTriggers();
        c_AutomationControl.isDisabled('Triggers');
    }
}